### PR TITLE
Activities branch with upgrade branch altogether

### PR DESCRIPTION
**Pull request by RotaruDan**
This PR rebased 'activities-branch' https://github.com/e-ucm/rage-analytics-backend/pull/108 with 'RotaruDan/upgradeScript' https://github.com/e-ucm/rage-analytics-backend/pull/110

### CODE REVIEW

**Comment by RotaruDan** [comment]
I'm using this branch to build a testing docker image with the same tag as the branch name (https://hub.docker.com/r/rotarudan/rage-analytics-backend/builds/) and check wether the recent changes work properly on private VMs

**Comment by RotaruDan** [comment]
If everything works properly, we should directly merge this ps with the corresponding closing of the other two 'activities-branch' and 'RotaruDan:upgradeScript'

**Comment by RotaruDan** [comment]
Tested with a full version of a DB, migrated successfully! Tested severall times, this might need further testing though :)

For now, the migration it's finally working!

**Comment by RotaruDan** [comment]
Everyting is ready as discussed, merging

**Comment by Synpheros** [comment]
Good Job!

**Pull request merged**
